import type { Metadata } from "next";
import { League_Spartan, Baloo_2 } from "next/font/google";
import "./globals.css";


const poppins = League_Spartan({
  subsets: ['latin-ext'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins'
})

const baloo2 = Baloo_2({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-baloo2'
})

// const satoshi = localFont({
//   src: '../fonts/Satoshi-Regular.woff2',
//   variable: '--font-satoshi'
// })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${poppins.variable} ${baloo2.variable}`}>
        {children}
      </body>
    </html>
  );
}
